Repository kubernetes-sigs/lws, pull requests merged in 2024-04, with the labels that each got.

#78 Fix comment error or typo
  pkg/controllers/leaderworkerset_controller.go
  pkg/controllers/pod_controller.go
  pkg/webhooks/leaderworkerset_webhook.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved, ok-to-test

#80 TestContainerRestarted method typo
  pkg/utils/pod/pod_utils_test.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved, ok-to-test

#81 remove generate from test-e2e
  Makefile
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved, ok-to-test

#82 Cleanup after e2e test
  Makefile
  pkg/controllers/leaderworkerset_controller_test.go
  test/e2e/e2e_test.go
  test/testutils/util.go
  test/testutils/validators.go
  test/testutils/wrappers.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/M, approved

#65 Support maxUnavailable in rollout
  api/leaderworkerset/v1/leaderworkerset_types.go
  cmd/main.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  config/samples/leaderworkerset_v1_leaderworkerset.yaml
  pkg/controllers/leaderworkerset_controller.go
  pkg/controllers/leaderworkerset_controller_test.go
  pkg/controllers/pod_controller.go
  pkg/controllers/pod_controller_test.go
  pkg/utils/pod/pod_utils.go
  pkg/utils/statefulset/statefulset_utils.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  pkg/webhooks/leaderworkerset_webhook.go
  pkg/webhooks/pod_webhook.go
  test/e2e/e2e_test.go
  test/integration/controllers/leaderworkerset_test.go
  test/integration/controllers/suite_test.go
  test/integration/webhooks/leaderworkerset_test.go
  test/testutils/util.go
  test/testutils/validators.go
  test/testutils/wrappers.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/XXL, approved, tide/merge-method-squash

#75 Fixed Saxml deployment documentation after ConfigMap change.
  docs/example/saxml/README.md
Labels: size/XS, cncf-cla: yes, lgtm, approved, kind/documentation, ok-to-test

#83 Add updatedReplicas to Status
  api/leaderworkerset/v1/leaderworkerset_types.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  pkg/controllers/leaderworkerset_controller.go
  test/e2e/suite_test.go
  test/integration/controllers/leaderworkerset_test.go
  test/testutils/util.go
  test/testutils/validators.go
Labels: kind/feature, cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash

#88 Use kubebuilder tag instead of webhook
  api/leaderworkerset/v1/leaderworkerset_types.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  pkg/webhooks/leaderworkerset_webhook.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved

#84 More E2E tests and general cleanup
  test/e2e/e2e_test.go
  test/integration/webhooks/pod_test.go
  test/testutils/util.go
  test/testutils/validators.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#93 add examples link in readme
  README.md
Labels: size/XS, cncf-cla: yes, lgtm, approved, kind/documentation

#90 fix: make generate error: unbound variable
  client-go/applyconfiguration/leaderworkerset/v1/leaderworkersetstatus.go
  hack/update-codegen.sh
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved

#91 cleanup: use kubebuilder marker instead of webhook
  api/leaderworkerset/v1/leaderworkerset_types.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  pkg/webhooks/leaderworkerset_webhook.go
  pkg/webhooks/pod_webhook_test.go
  test/integration/webhooks/leaderworkerset_test.go
  test/testutils/wrappers.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/M, approved

#95 feat: add kubeconfig value
  cmd/main.go
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-ok-to-test

#99 Fix maxUnavailable couldn't be bigger than replicas
  pkg/controllers/leaderworkerset_controller.go
  pkg/webhooks/leaderworkerset_webhook.go
  test/integration/controllers/leaderworkerset_test.go
  test/integration/webhooks/leaderworkerset_test.go
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, approved

#101 feat: add event recorder event for lws controller
  pkg/controllers/leaderworkerset_controller.go
  pkg/utils/constants/constants.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#108 fix: fix ci error
  pkg/controllers/leaderworkerset_controller.go
  pkg/utils/constants/constants.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#103 Adding unit tests for leaderworkerset_webhook
  pkg/webhooks/leaderworkerset_webhook_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash, ok-to-test

#105 Add publish not ready addresses
  pkg/controllers/leaderworkerset_controller.go
  test/testutils/validators.go
Labels: kind/feature, size/XS, cncf-cla: yes, lgtm, approved, tide/merge-method-squash

#107 Remove maxSurge
  api/leaderworkerset/v1/leaderworkerset_types.go
  api/leaderworkerset/v1/zz_generated.deepcopy.go
  client-go/applyconfiguration/leaderworkerset/v1/rollingupdateconfiguration.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  config/samples/leaderworkerset_v1_leaderworkerset.yaml
  pkg/controllers/leaderworkerset_controller_test.go
  pkg/webhooks/leaderworkerset_webhook.go
  test/integration/webhooks/leaderworkerset_test.go
  test/testutils/wrappers.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/M, approved, tide/merge-method-squash

#109 Remove unnecessary notFoundError log
  pkg/controllers/pod_controller.go
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#111 Change the semantics of leaderWorkerSet Replicas
  api/leaderworkerset/v1/leaderworkerset_types.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  pkg/controllers/leaderworkerset_controller.go
  test/integration/controllers/leaderworkerset_test.go
  test/testutils/util.go
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, approved

#112 use t.Errorf instead of t.Fatalf
  pkg/utils/utils_test.go
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved, ok-to-test

#114 Update lws version for installation
  docs/setup/install.md
Labels: size/XS, cncf-cla: yes, lgtm, approved

#120 Downgrading controller-runtime to 0.16.3
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#121 Simplify the partition update model
  pkg/controllers/leaderworkerset_controller.go
  test/integration/controllers/leaderworkerset_test.go
  test/testutils/validators.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved
