Repository kubernetes-sigs/lws, pull requests merged in 2024-05, with the labels that each got.

#126 add kep template
  kep/NNNN-Template/README.md
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/documentation, ok-to-test

#130 fix example url in README.md
  README.md
Labels: size/XS, cncf-cla: yes, lgtm, approved, kind/documentation, ok-to-test

#131 Add KEP template update/verify tool
  Makefile
  hack/.notableofcontents
  hack/update-toc.sh
  hack/verify-toc.sh
  keps/NNNN-Template/README.md
  keps/NNNN-Template/kep.yaml
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved

#98 Support maxSurge in rolling update
  api/leaderworkerset/v1/leaderworkerset_types.go
  api/leaderworkerset/v1/zz_generated.deepcopy.go
  client-go/applyconfiguration/leaderworkerset/v1/rollingupdateconfiguration.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  pkg/controllers/leaderworkerset_controller.go
  pkg/controllers/leaderworkerset_controller_test.go
  pkg/controllers/pod_controller.go
  pkg/webhooks/leaderworkerset_webhook.go
  pkg/webhooks/leaderworkerset_webhook_test.go
  test/e2e/e2e_test.go
  test/integration/controllers/leaderworkerset_test.go
  test/integration/webhooks/leaderworkerset_test.go
  test/testutils/util.go
  test/testutils/validators.go
  test/testutils/wrappers.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/XXL, approved

#138 fix: handle construct worker sts configuration error promptly
  pkg/controllers/pod_controller.go
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#133 add vllm distributed inference examples
  docs/example/vllm/README.md
  docs/example/vllm/build/Dockerfile
  docs/example/vllm/build/ray_init.sh
  docs/example/vllm/lws.yaml
  docs/example/vllm/service.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/documentation, ok-to-test

#137 Fix flaky test in maxSurge integration tests
  test/integration/controllers/leaderworkerset_test.go
Labels: size/XS, cncf-cla: yes, kind/cleanup, kind/flake, lgtm, approved

#140 chore: upgrade e2e kind version
  Makefile
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#127 add kep-115 Subgroup support
  keps/115-Subgroup-support/README.md
  keps/115-Subgroup-support/kep.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash, ok-to-test

#145 Add docs for rollout strategy
  README.md
  docs/example/sample/README.md
  docs/examples/sample/README.md
  docs/examples/sample/horizontal-pod-autoscaler.yaml
  docs/examples/sample/lws-exclusive-placement.yaml
  docs/examples/sample/lws-multi-template.yaml
  docs/examples/sample/lws-restart-policy.yaml
  docs/examples/sample/lws-rollout-strategy.yaml
  docs/examples/sample/lws.yaml
  docs/examples/saxml/README.md
  docs/examples/saxml/configmap.yaml
  docs/examples/saxml/lws.yaml
  docs/examples/saxml/service.yaml
  docs/examples/vllm/README.md
  docs/examples/vllm/build/Dockerfile
  docs/examples/vllm/build/ray_init.sh
  docs/examples/vllm/lws.yaml
  docs/examples/vllm/service.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash, kind/documentation

#144 Add leader address environment variable injection
  api/leaderworkerset/v1/leaderworkerset_types.go
  pkg/utils/accelerators/tpu.go
  pkg/utils/pod/pod_utils.go
  pkg/utils/pod/pod_utils_test.go
  pkg/webhooks/pod_webhook.go
  test/integration/webhooks/pod_test.go
  test/testutils/util.go
  test/testutils/wrappers.go
Labels: kind/feature, cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash, ok-to-test

#136 kep-135 add startup policy api
  keps/135-startup-policy/README.md
  keps/135-startup-policy/kep.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash, kind/documentation

#151 Remove resource limit for auth proxy
  config/default/manager_auth_proxy_patch.yaml
Labels: size/XS, cncf-cla: yes, lgtm, approved

#152 Switch the order of env var for LWS_LEADER_ADDRESS
  pkg/utils/pod/pod_utils.go
  test/integration/webhooks/pod_test.go
  test/testutils/util.go
  test/testutils/wrappers.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#146 Adding Upgrade in Progress Condition
  api/leaderworkerset/v1/leaderworkerset_types.go
  pkg/controllers/leaderworkerset_controller.go
  pkg/controllers/leaderworkerset_controller_test.go
  test/integration/controllers/leaderworkerset_test.go
  test/testutils/validators.go
Labels: kind/feature, cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash, ok-to-test

#125 Adding Subgroup support
  api/leaderworkerset/v1/leaderworkerset_types.go
  api/leaderworkerset/v1/zz_generated.deepcopy.go
  client-go/applyconfiguration/leaderworkerset/v1/leaderworkertemplate.go
  client-go/applyconfiguration/leaderworkerset/v1/subgrouppolicy.go
  client-go/applyconfiguration/utils.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  keps/115-Subgroup-support/README.md
  pkg/controllers/leaderworkerset_controller.go
  pkg/controllers/leaderworkerset_controller_test.go
  pkg/controllers/pod_controller.go
  pkg/controllers/pod_controller_test.go
  pkg/utils/accelerators/tpu.go
  pkg/utils/accelerators/tpu_test.go
  pkg/webhooks/leaderworkerset_webhook.go
  pkg/webhooks/pod_webhook.go
  pkg/webhooks/pod_webhook_test.go
  test/e2e/e2e_test.go
  test/integration/webhooks/leaderworkerset_test.go
  test/integration/webhooks/pod_test.go
  test/testutils/util.go
  test/testutils/validators.go
  test/testutils/wrappers.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/XXL, approved, tide/merge-method-squash, ok-to-test
