Repository kubernetes-sigs/lws, pull requests merged in 2024-11, with the labels that each got.

#244 Changed log level to 2
  config/default/manager_auth_proxy_patch.yaml
Labels: kind/bug, size/XS, cncf-cla: yes, lgtm, approved

#250 change to not use NetworkConfig in hash calculation if it has default value
  pkg/utils/utils.go
Labels: kind/bug, size/XS, cncf-cla: yes, lgtm, approved

#251 Added validation for subdomainPolicy values
  api/leaderworkerset/v1/leaderworkerset_types.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
Labels: kind/bug, size/XS, cncf-cla: yes, lgtm, approved

#252 Automated cherry pick of #250: change to not use NetworkConfig in hash calculation if it has default value
  pkg/utils/utils.go
Labels: size/XS, cncf-cla: yes, lgtm, approved

#253 changed cherry pick script to be executable
  hack/cherry_pick_pull.sh
Labels: kind/bug, size/XS, cncf-cla: yes, lgtm, approved

#249 add pods finalizer update rbac to allow lws to run in openshift
  config/rbac/role.yaml
  pkg/controllers/pod_controller.go
Labels: kind/bug, size/XS, cncf-cla: yes, lgtm, approved

#255 Update installation instructions for release 0.4.2
  docs/setup/install.md
Labels: size/XS, cncf-cla: yes, lgtm, approved

#263 Unify Leader Election Namespace with Deployment Namespace
  cmd/main.go
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#273 Updating OWNERS file
  OWNERS
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved
