Repository kubernetes-sigs/lws, pull requests merged in 2024-07, with the labels that each got.

#171 docs: add LeaderWorkerSet API reference
  Makefile
  Makefile-deps.mk
  docs/reference/leaderworkerset.v1.md
  hack/genref/config.yaml
  hack/genref/markdown/members.tpl
  hack/genref/markdown/pkg.tpl
  hack/genref/markdown/type.tpl
Labels: cncf-cla: yes, size/XL, lgtm, approved, ok-to-test

#174 Add example for llama.cpp
  docs/examples/llamacpp/README.md
  docs/examples/llamacpp/dev/tasks/load-images-into-docker
  docs/examples/llamacpp/dev/tasks/run-in-kind
  docs/examples/llamacpp/dev/tasks/start-blobserver
  docs/examples/llamacpp/dev/tasks/stop-blobserver
  docs/examples/llamacpp/docker-bake.hcl
  docs/examples/llamacpp/images/bartowski/Dockerfile
  docs/examples/llamacpp/images/clichat/Dockerfile
  docs/examples/llamacpp/images/llamacpp-leader/Dockerfile
  docs/examples/llamacpp/images/llamacpp-worker/Dockerfile
  docs/examples/llamacpp/k8s/lws.yaml
  docs/examples/llamacpp/k8s/service.yaml
  docs/examples/llamacpp/tools/blobserver/cmd/blobserver/main.go
  docs/examples/llamacpp/tools/blobserver/go.mod
  docs/examples/llamacpp/tools/blobserver/go.sum
  docs/examples/llamacpp/tools/clichat/cmd/clichat/main.go
  docs/examples/llamacpp/tools/clichat/go.mod
  docs/examples/llamacpp/tools/clichat/go.sum
  docs/examples/llamacpp/tools/llamacpp-leader/cmd/llamacpp-leader/main.go
  docs/examples/llamacpp/tools/llamacpp-leader/go.mod
  docs/examples/llamacpp/tools/llamacpp-leader/go.sum
Labels: cncf-cla: yes, size/XL, lgtm, approved

#180 add verify job and fix code where it fails
  Makefile
  keps/115-Subgroup-support/README.md
  keps/135-startup-policy/README.md
  keps/NNNN-Template/README.md
  test/e2e/e2e_test.go
  test/integration/controllers/leaderworkerset_test.go
  test/testutils/util.go
  test/testutils/validators.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#183 set golangci-lint for 15 minutes to be same as jobset
  Makefile
Labels: size/XS, cncf-cla: yes, lgtm, approved
