Repository kubernetes-sigs/lws, pull requests merged in 2024-10, with the labels that each got.

#209 Injecting TPU_NAME environment variable
  pkg/utils/accelerators/tpu.go
  pkg/utils/accelerators/tpu_test.go
  test/testutils/util.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/S, approved

#229 Creating new workerStatefulSet instead of patching when updating LWS template
  pkg/controllers/pod_controller.go
  test/integration/controllers/leaderworkerset_test.go
  test/testutils/util.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash

#233 Update KEP #173 to reflect implementation
  keps/173-headless-service-per-replica/README.md
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved, tide/merge-method-squash

#235 Add cherry-pick script
  hack/cherry_pick_pull.sh
Labels: cncf-cla: yes, size/L, lgtm, approved
