Repository kubernetes-sigs/lws, pull requests merged in 2024-06, with the labels that each got.

#156 Ignore controller-runtime upgrade
  .github/dependabot.yml
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#155 Chore: convert required fields to optional
  api/leaderworkerset/v1/leaderworkerset_types.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  pkg/webhooks/pod_webhook.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved

#157 chore: update e2e k8s version to v1.30.0
  Makefile
Labels: kind/feature, size/XS, cncf-cla: yes, lgtm, approved

#150 feat: support startup policy
  api/leaderworkerset/v1/leaderworkerset_types.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  go.mod
  go.sum
  pkg/controllers/leaderworkerset_controller.go
  pkg/controllers/pod_controller.go
  test/integration/controllers/leaderworkerset_test.go
  test/integration/webhooks/leaderworkerset_test.go
  test/testutils/util.go
  test/testutils/validators.go
  test/testutils/wrappers.go
Labels: kind/feature, cncf-cla: yes, size/L, lgtm, approved

#160 Update the lws version of the installation guide
  docs/setup/install.md
Labels: size/XS, cncf-cla: yes, lgtm, approved

#163 add leader elect args
  cmd/main.go
  config/manager/manager.yaml
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#166 Add executable permission to the example script ray_init.sh
  docs/examples/vllm/build/ray_init.sh
Labels: kind/bug, size/XS, cncf-cla: no, ok-to-test
