Repository kubernetes-sigs/lws, pull requests merged in 2024-12, with the labels that each got.

#282 Use the namespace of the service account
  cmd/main.go
  config/default/manager_auth_proxy_patch.yaml
  docs/setup/install.md
  pkg/utils/utils.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved

#285 add doc to say how to install in a different namespace
  docs/setup/install.md
Labels: cncf-cla: yes, lgtm, size/S, approved, kind/documentation

#261 add KEP 238, to add controller revision
  keps/238-controller-revision/README.md
  keps/238-controller-revision/kep.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-merge, kind/documentation

#290 address non linear parsing cve by upgrading golang net
  go.mod
  go.sum
Labels: kind/bug, cncf-cla: yes, lgtm, size/M, approved

#293 Remove `namespace` arg from manager command
  charts/lws/templates/manager/deployment.yaml
Labels: kind/bug, size/XS, cncf-cla: yes, lgtm, approved, ok-to-test

#277 Add Controller Revision (Implementation of KEP #238)
  api/leaderworkerset/v1/leaderworkerset_types.go
  config/rbac/role.yaml
  pkg/controllers/leaderworkerset_controller.go
  pkg/controllers/leaderworkerset_controller_test.go
  pkg/controllers/pod_controller.go
  pkg/controllers/pod_controller_test.go
  pkg/utils/revision/revision_utils.go
  pkg/utils/revision/revision_utils_test.go
  pkg/utils/utils.go
  test/e2e/e2e_test.go
  test/testutils/util.go
  test/testutils/validators.go
  test/testutils/wrappers.go
Labels: kind/feature, cncf-cla: yes, size/XL, lgtm, approved
