Repository kubernetes-sigs/lws, pull requests merged in 2024-09, with the labels that each got.

#207 Bump kubernetes dependencies to v0.31.x.
  .golangci.yaml
  Makefile
  Makefile-deps.mk
  client-go/applyconfiguration/leaderworkerset/v1/leaderworkerset.go
  client-go/applyconfiguration/leaderworkerset/v1/leaderworkersetspec.go
  client-go/applyconfiguration/leaderworkerset/v1/leaderworkersetstatus.go
  client-go/applyconfiguration/leaderworkerset/v1/leaderworkertemplate.go
  client-go/applyconfiguration/leaderworkerset/v1/rollingupdateconfiguration.go
  client-go/applyconfiguration/leaderworkerset/v1/rolloutstrategy.go
  client-go/applyconfiguration/leaderworkerset/v1/subgrouppolicy.go
  client-go/applyconfiguration/utils.go
  client-go/clientset/versioned/fake/clientset_generated.go
  client-go/clientset/versioned/typed/leaderworkerset/v1/fake/fake_leaderworkerset.go
  client-go/clientset/versioned/typed/leaderworkerset/v1/leaderworkerset.go
  client-go/informers/externalversions/factory.go
  client-go/listers/leaderworkerset/v1/leaderworkerset.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XXL, approved

#208 feature: Add group size environment variable injection
  api/leaderworkerset/v1/leaderworkerset_types.go
  pkg/utils/pod/pod_utils.go
  pkg/utils/pod/pod_utils_test.go
  test/integration/webhooks/pod_test.go
  test/testutils/util.go
  test/testutils/wrappers.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved

#212 simply llama.cpp example
  docs/examples/llamacpp/k8s/lws.yaml
  docs/examples/llamacpp/tools/llamacpp-leader/cmd/llamacpp-leader/main.go
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#211 Make llama.cpp example become avaliable on macOS
  docs/examples/llamacpp/dev/tasks/load-images-into-docker
  docs/examples/llamacpp/dev/tasks/stop-blobserver
  docs/examples/llamacpp/docker-bake.hcl
  docs/examples/llamacpp/images/bartowski/Dockerfile
Labels: kind/bug, cncf-cla: yes, lgtm, size/S, approved

#197 Adding SubdomainPolicy to support a service per replica
  api/leaderworkerset/v1/leaderworkerset_types.go
  api/leaderworkerset/v1/zz_generated.deepcopy.go
  client-go/applyconfiguration/leaderworkerset/v1/leaderworkersetspec.go
  client-go/applyconfiguration/leaderworkerset/v1/networkconfig.go
  client-go/applyconfiguration/utils.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  pkg/controllers/leaderworkerset_controller.go
  pkg/controllers/pod_controller.go
  pkg/utils/controller/controller_utils.go
  pkg/utils/pod/pod_utils.go
  pkg/utils/utils.go
  pkg/webhooks/leaderworkerset_webhook.go
  pkg/webhooks/pod_webhook.go
  test/e2e/e2e_test.go
  test/integration/controllers/leaderworkerset_test.go
  test/integration/webhooks/leaderworkerset_test.go
  test/integration/webhooks/pod_test.go
  test/testutils/util.go
  test/testutils/validators.go
  test/testutils/wrappers.go
Labels: kind/feature, cncf-cla: yes, size/XL, lgtm, approved, tide/merge-method-squash

#214 Deprecated DefaultRestartPolicy with NoneRestartPolicy
  api/leaderworkerset/v1/leaderworkerset_types.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  pkg/controllers/leaderworkerset_controller_test.go
  pkg/webhooks/leaderworkerset_webhook.go
  test/e2e/e2e_test.go
  test/integration/controllers/leaderworkerset_test.go
  test/integration/webhooks/leaderworkerset_test.go
  test/testutils/wrappers.go
Labels: kind/feature, cncf-cla: yes, kind/cleanup, lgtm, size/M, approved

#217 Update installation guide
  docs/setup/install.md
Labels: size/XS, cncf-cla: yes, lgtm, approved

#226 Add support to install lws at an arbitrary namespace
  cmd/main.go
  config/default/manager_auth_proxy_patch.yaml
  docs/setup/install.md
  pkg/cert/cert.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved

#227 feat: add build arg to docker buildx
  Makefile
Labels: kind/feature, size/XS, cncf-cla: yes, lgtm, approved, ok-to-test
