Repository kubernetes-sigs/lws, pull requests merged in 2024-08, with the labels that each got.

#186 Fix missing startupPolicy in applyConfiguration
  client-go/applyconfiguration/leaderworkerset/v1/leaderworkersetspec.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved

#185 updating vllm docs to use llama3 405B as example
  docs/examples/vllm/README.md
  docs/examples/vllm/build/Dockerfile
  docs/examples/vllm/lws.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, kind/documentation, ok-to-test

#190 No worker sts when size=1
  Makefile
  pkg/controllers/leaderworkerset_controller.go
  pkg/controllers/pod_controller.go
  test/e2e/e2e_test.go
  test/integration/controllers/leaderworkerset_test.go
  test/testutils/util.go
  test/testutils/validators.go
  test/testutils/wrappers.go
Labels: kind/feature, cncf-cla: yes, size/L, lgtm, approved

#191 Bump cert-controller to v0.11.0
  .github/dependabot.yml
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  go.mod
  go.sum
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XXL, approved

#194 add golangci config to project
  .golangci.yaml
  pkg/utils/accelerators/tpu.go
  pkg/utils/accelerators/tpu_test.go
  pkg/webhooks/leaderworkerset_webhook.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/M, approved

#188 Headless Service Per Replica KEP
  keps/173-headless-service-per-replica/README.md
  keps/173-headless-service-per-replica/kep.yaml
Labels: kind/feature, cncf-cla: yes, size/L, lgtm, approved

#196 fix make generate
  client-go/applyconfiguration/leaderworkerset/v1/leaderworkersetstatus.go
  hack/update-codegen.sh
Labels: kind/bug, cncf-cla: yes, lgtm, size/M, approved

#200 We should not import from k8s/kubernetes.
  go.mod
  go.sum
  pkg/controllers/pod_controller.go
  pkg/utils/pod/pod_utils.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/M, approved
