Repository kubernetes-sigs/lws, pull requests merged in 2024-03, with the labels that each got.

#11 Project refactor work
  .gitignore
  Dockerfile
  Makefile
  PROJECT
  client-go/applyconfiguration/leaderworkerset/v1/leaderworkertemplate.go
  client-go/applyconfiguration/utils.go
  client-go/clientset/versioned/clientset.go
  client-go/clientset/versioned/fake/clientset_generated.go
  client-go/clientset/versioned/fake/register.go
  client-go/clientset/versioned/scheme/register.go
  client-go/clientset/versioned/typed/leaderworkerset/v1/fake/fake_leaderworkerset.go
  client-go/clientset/versioned/typed/leaderworkerset/v1/fake/fake_leaderworkerset_client.go
  client-go/clientset/versioned/typed/leaderworkerset/v1/leaderworkerset.go
  client-go/clientset/versioned/typed/leaderworkerset/v1/leaderworkerset_client.go
  client-go/informers/externalversions/factory.go
  client-go/informers/externalversions/generic.go
  client-go/informers/externalversions/internalinterfaces/factory_interfaces.go
  client-go/informers/externalversions/leaderworkerset/interface.go
  client-go/informers/externalversions/leaderworkerset/v1/interface.go
  client-go/informers/externalversions/leaderworkerset/v1/leaderworkerset.go
  client-go/listers/leaderworkerset/v1/leaderworkerset.go
  cmd/main.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  cover.out
  go.mod
  hack/update-codegen.sh
  pkg/cert/cert.go
  pkg/commonutils/statefulset_utils.go
  pkg/commonutils/utils_test.go
  pkg/controller/controller_test.go
  pkg/controller/controller_utils.go
  pkg/controller/leaderworkerset_controller.go
  pkg/controller/pod_controller.go
  pkg/webhook/pod_webhook.go
  pkg/webhook/webhook_utils.go
  test/integration/controller/leaderworkerset_controller_test.go
  test/integration/controller/suite_test.go
  test/integration/webhook/leaderworkerset_webhook_integration_test.go
  test/integration/webhook/pod_webhook_integration_test.go
  test/integration/webhook/webhook_suite_test.go
  test/testutils/util.go
  test/testutils/validators.go
  test/testutils/wrappers.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, tide/merge-method-squash

#10 Add dependabot
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/CLEANUP.md
  .github/ISSUE_TEMPLATE/ENHANCEMENT.md
  .github/ISSUE_TEMPLATE/SUPPORT.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash

#28 Add integration test
  Makefile
Labels: kind/feature, cncf-cla: yes, lgtm, size/S, approved, tide/merge-method-squash

#30 Add shortname lws for API & sort out build image command
  .gitignore
  Makefile
  api/leaderworkerset/v1/leaderworkerset_types.go
  artifacts/manifests.yaml
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
Labels: kind/feature, cncf-cla: yes, lgtm, size/XXL, approved, tide/merge-method-squash

#31 nominate kerthcet as approver
  OWNERS
Labels: size/XS, cncf-cla: yes, lgtm, approved, kind/documentation

#32 Move the tpu related logic to a separate folder
  pkg/controller/pod_controller.go
  pkg/utils/accelerators/tpu.go
  pkg/utils/statefulset/statefulset_utils.go
  pkg/utils/statefulset/statefulset_utils_test.go
  pkg/webhook/pod_webhook.go
  pkg/webhook/webhook_utils.go
  test/testutils/util.go
  test/testutils/validators.go
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved, tide/merge-method-squash, ok-to-test

#33 Add documentation part-1
  README.md
Labels: cncf-cla: yes, lgtm, size/S, approved, tide/merge-method-squash, kind/documentation, needs-ok-to-test

#37 Update readme expression
  README.md
Labels: cncf-cla: yes, lgtm, size/S, approved, kind/documentation, ok-to-test

#38 Fix Available and Processing condition should not both be true
  pkg/controller/controller_utils.go
  test/integration/controller/leaderworkerset_controller_test.go
  test/testutils/validators.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/M, approved

#36 added unit tests for controller utils, tpu, and webhook utils
  pkg/controller/controller_test.go
  pkg/utils/accelerators/tpu.go
  pkg/utils/accelerators/tpu_test.go
  pkg/utils/statefulset/statefulset_utils.go
  pkg/utils/statefulset/statefulset_utils_test.go
  pkg/webhook/webhook_utils_test.go
  test/testutils/wrappers.go
Labels: cncf-cla: yes, size/XL, lgtm, approved, tide/merge-method-squash, ok-to-test

#40 Fix docker build error
  Dockerfile
  go.mod
  go.sum
  hack/internal/tools.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/M, approved

#41 Cleaning up the pod utility functions into their own pkg
  pkg/controller/controller_utils.go
  pkg/controller/leaderworkerset_controller.go
  pkg/controller/leaderworkerset_controller_test.go
  pkg/controller/pod_controller.go
  pkg/utils/pod/pod_utils.go
  pkg/utils/pod/pod_utils_test.go
Labels: cncf-cla: yes, size/XL, kind/cleanup, lgtm, approved

#42 Fix test-infra failed to build image
  Dockerfile
  Makefile
  cloudbuild.yaml
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/M, approved

#43 Cleanup code package structure and file names
  api/leaderworkerset/v1/leaderworkerset_types.go
  api/leaderworkerset/v1/zz_generated.deepcopy.go
  cmd/main.go
  pkg/controllers/leaderworkerset_controller.go
  pkg/controllers/leaderworkerset_controller_test.go
  pkg/controllers/pod_controller.go
  pkg/webhook/webhook_utils.go
  pkg/webhooks/leaderworkerset_webhook.go
  pkg/webhooks/pod_webhook.go
  pkg/webhooks/pod_webhook_test.go
  test/integration/controllers/leaderworkerset_test.go
  test/integration/controllers/suite_test.go
  test/integration/webhooks/leaderworkerset_test.go
  test/integration/webhooks/pod_test.go
  test/integration/webhooks/suite_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved, tide/merge-method-squash

#49 Fix: build image error
  Dockerfile
  pkg/controllers/leaderworkerset_controller.go
  pkg/controllers/leaderworkerset_controller_test.go
  pkg/controllers/pod_controller.go
  pkg/controllers/pod_controller_test.go
Labels: kind/bug, cncf-cla: yes, size/XL, kind/cleanup, lgtm, approved

#52 Add rupliu as reviewer
  OWNERS
Labels: size/XS, cncf-cla: yes, lgtm, approved, kind/documentation, needs-ok-to-test

#58 Replace leader-worker-set to lws
  config/certmanager/certificate.yaml
  config/default/kustomization.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/leaderworkerset_editor_role.yaml
  config/rbac/leaderworkerset_viewer_role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/samples/leaderworkerset_exclusiveplacement.yaml
  config/samples/leaderworkerset_multi_template.yaml
  config/samples/leaderworkerset_tpu.yaml
  config/samples/leaderworkerset_v1_leaderworkerset.yaml
  config/webhook/service.yaml
  pkg/cert/cert.go
  pkg/controllers/leaderworkerset_controller.go
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved

#54 Add installation guide
  README.md
  docs/setup/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash, kind/documentation

#39 Feat: Rollout API
  api/leaderworkerset/v1/leaderworkerset_types.go
  api/leaderworkerset/v1/zz_generated.deepcopy.go
  client-go/applyconfiguration/leaderworkerset/v1/leaderworkersetspec.go
  client-go/applyconfiguration/leaderworkerset/v1/rollingupdateconfiguration.go
  client-go/applyconfiguration/leaderworkerset/v1/rolloutstrategy.go
  client-go/applyconfiguration/utils.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  pkg/webhooks/leaderworkerset_webhook.go
  test/integration/webhooks/leaderworkerset_test.go
  test/testutils/wrappers.go
Labels: kind/feature, cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#60 Cleanup deprecated package k8s.io/utils/pointer
  pkg/controllers/leaderworkerset_controller.go
  pkg/controllers/pod_controller.go
  pkg/webhooks/leaderworkerset_webhook.go
  test/integration/controllers/leaderworkerset_test.go
  test/testutils/util.go
  test/testutils/wrappers.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved, ok-to-test

#61 Fix TPU env var assignment when leader doesn't request TPUs
  pkg/controllers/leaderworkerset_controller.go
  pkg/controllers/pod_controller.go
  pkg/utils/accelerators/tpu.go
  pkg/utils/accelerators/tpu_test.go
  pkg/webhooks/pod_webhook.go
  test/integration/webhooks/pod_test.go
  test/testutils/util.go
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, approved

#59 added documentation for deploying SaxML multihost using LWS
  docs/example/saxml/README.md
  docs/example/saxml/configmap.yaml
  docs/example/saxml/lws.yaml
  docs/example/saxml/service.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/documentation, ok-to-test

#70 Migrate go version
  go.mod
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#67 added documentation on leaderworkerset features
  docs/example/sample/README.md
  docs/example/sample/horizontal-pod-autoscaler.yaml
  docs/example/sample/lws-exclusive-placement.yaml
  docs/example/sample/lws-multi-template.yaml
  docs/example/sample/lws-restart-policy.yaml
  docs/example/sample/lws.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/documentation, ok-to-test

#68 allowed prometheus to gather metrics
  Makefile
  config/components/prometheus/kustomization.yaml
  config/components/prometheus/monitor.yaml
  config/components/prometheus/role.yaml
  config/prometheus/kustomization.yaml
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#71 Add E2E test
  Makefile
  test/e2e/config/image_pull_policy.yaml
  test/e2e/config/kustomization.yaml
  test/e2e/e2e-test.sh
  test/e2e/e2e_test.go
  test/e2e/suite_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved, ok-to-test

#72 Remove vestigial Getwd()
  test/e2e/suite_test.go
Labels: size/XS, cncf-cla: yes, lgtm, approved, ok-to-test

#73 SaxML ConfigMap doesn't need to specify the model field
  docs/example/saxml/README.md
  docs/example/saxml/configmap.yaml
Labels: size/XS, cncf-cla: yes, lgtm, approved, ok-to-test

#76 E2E test now waits for webhook to complete setup
  test/e2e/suite_test.go
Labels: kind/bug, cncf-cla: yes, size/M, ok-to-test
