Repository kubernetes-sigs/lws, pull requests merged in 2025-04, with the labels that each got.

#483 use a bigger machine for cloud build
  cloudbuild.yaml
Labels: kind/bug, size/XS, cncf-cla: yes, lgtm, approved

#485 [CI] Add more verify include gomod, fmt, and generate-apiref
  Makefile
  site/content/en/docs/reference/leaderworkerset.v1.md
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/M, approved

#486 docs: remove the use of Downward API for LWS_WORKER_INDEX
  docs/examples/sglang/lws.yaml
  site/content/en/docs/reference/labels-annotations-and-environment-variables.md
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/M, approved

#487 Update helm install documentation
  site/content/en/docs/installation/_index.md
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#494 [Docs] Fixed location of vLLM script on TPU image
  docs/examples/vllm/TPU/lws.yaml
Labels: size/XS, cncf-cla: yes, lgtm, approved, kind/documentation

#490 Fix UpdateInProgress conditions for newly created LWS
  pkg/controllers/leaderworkerset_controller.go
  test/integration/controllers/leaderworkerset_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/S, approved

#505 Update RELEASE.md
  .github/ISSUE_TEMPLATE/new-release.md
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved

#503 Add an example of using OCI to the Helm installation guide
  charts/lws/README.md
  site/content/en/docs/installation/_index.md
Labels: cncf-cla: yes, lgtm, size/M, approved, kind/documentation

#504 Add `prepare-release-branch` in Makefile to update versions automatically
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  Makefile
  charts/lws/Chart.yaml
  site/config.toml
  site/content/en/docs/installation/_index.md
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/M, approved

#478 Inject certs for metrics endpoint when cert-manager is enabled
  charts/lws/templates/certmanager/certificate.yaml
  charts/lws/templates/certmanager/certificatemetrics.yaml
  charts/lws/templates/manager/deployment.yaml
  charts/lws/templates/prometheus/monitor.yaml
  config/certmanager/certificate-metrics.yaml
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/components/prometheus/kustomization.yaml
  config/components/prometheus/monitor_tls_patch.yaml
  config/default/cert_metrics_manager_patch.yaml
  config/default/kustomization.yaml
Labels: kind/feature, cncf-cla: yes, size/L, lgtm, approved

#517 Add LWS configuration in Helm Charts
  charts/lws/templates/manager/configmap.yaml
  charts/lws/templates/manager/deployment.yaml
  config/manager/controller_manager_config.yaml
Labels: kind/feature, cncf-cla: yes, lgtm, size/S, approved

#518 Run e2e tests also when cert-manager is enabled
  Makefile
  hack/e2e-test.sh
  test/e2e/config/certmanager/image_pull_policy.yaml
  test/e2e/config/certmanager/kustomization.yaml
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved

#522 Removing SaxML docs
  docs/examples/saxml/README.md
  docs/examples/saxml/configmap.yaml
  docs/examples/saxml/lws.yaml
  site/content/en/docs/examples/saxml.md
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/documentation
