Repository kubernetes-sigs/lws, pull requests merged in 2025-02, with the labels that each got.

#357 updating version in docs
  charts/lws/Chart.yaml
  docs/setup/install.md
Labels: size/XS, cncf-cla: yes, lgtm, approved, kind/documentation

#358 Updating docs on main branch
  charts/lws/Chart.yaml
  docs/setup/install.md
Labels: size/XS, cncf-cla: yes, lgtm, approved, kind/documentation

#360 Fix for odd numbers of arguments passed as key-value pairs for logging issue
  pkg/controllers/pod_controller.go
Labels: size/XS, cncf-cla: yes, lgtm, approved, ok-to-test

#365 Fix redundant comments in `config/crd/kustomization.yaml`
  config/crd/kustomization.yaml
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#356 Adding User Guide for TensorRT-LLM
  docs/examples/tensorrt-llm/README.md
  docs/examples/tensorrt-llm/build/Dockerfile
  docs/examples/tensorrt-llm/build/install_model.sh
  docs/examples/tensorrt-llm/build/server.py
  docs/examples/tensorrt-llm/lws.yaml
  docs/examples/tensorrt-llm/rbac.yaml
  docs/examples/tensorrt-llm/service.yaml
Labels: cncf-cla: yes, size/XL, lgtm, approved, kind/documentation

#362 Add feature gate introduction for MaxUnavailableStatefulSet
  docs/setup/install.md
Labels: cncf-cla: yes, lgtm, size/S, approved

#367 Add adopters, integrations, talks
  README.md
  docs/showcase.md
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved

#361 Deprecate flags as the recommended path is to pass configuration file
  Makefile
  cmd/main.go
  cmd/main_test.go
  pkg/controllers/leaderworkerset_controller.go
  pkg/webhooks/leaderworkerset_webhook.go
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved, ok-to-test

#343 Add user-agent with semantic version
  Dockerfile
  Makefile
  cmd/main.go
  pkg/utils/useragent/useragent.go
  pkg/utils/useragent/useragent_test.go
  pkg/version/version.go
Labels: kind/feature, cncf-cla: yes, size/L, lgtm, approved

#375 Update k8s binary dependencies to align with 1.32
  Makefile
  Makefile-deps.mk
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved, ok-to-test

#373 doc: Add terraform based EKS Blueprints pattern for multi-node inference
  docs/showcase.md
Labels: size/XS, cncf-cla: yes, lgtm, approved, tide/merge-method-squash, ok-to-test

#374 Add missing external types to apply configurations
  client-go/applyconfiguration/leaderworkerset/v1/leaderworkertemplate.go
  hack/update-codegen.sh
Labels: kind/bug, cncf-cla: yes, lgtm, size/S, approved, kind/api-change

#380 Updating the adopters page
  docs/adoption/README.md
  docs/showcase.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#381 Fix the error link of adopter page
  README.md
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#377 Adding User Guide for SGLang
  docs/examples/sglang/README.md
  docs/examples/sglang/lws.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/documentation

#383 Ignore LeaderElectionNamespace in cmd unit tests as it is dynamic
  cmd/main_test.go
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#384 Update all the examples to combine the `service.yaml` into the `lws.yaml`
  docs/examples/llamacpp/README.md
  docs/examples/llamacpp/k8s/lws.yaml
  docs/examples/llamacpp/k8s/service.yaml
  docs/examples/saxml/README.md
  docs/examples/saxml/lws.yaml
  docs/examples/saxml/service.yaml
  docs/examples/tensorrt-llm/README.md
  docs/examples/tensorrt-llm/lws.yaml
  docs/examples/tensorrt-llm/service.yaml
  docs/examples/vllm/GPU/README.md
  docs/examples/vllm/GPU/lws.yaml
  docs/examples/vllm/GPU/service.yaml
  docs/examples/vllm/TPU/README.md
  docs/examples/vllm/TPU/lws.yaml
  docs/examples/vllm/TPU/service.yaml
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved

#389 update k8s utils
  go.mod
  go.sum
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#378 Allow pass through of additional params to "ray start" in ray_init.sh
  docs/examples/vllm/build/ray_init.sh
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved

#394 Fix infinite StatefulSet creation loops by validate leader annotations
  pkg/controllers/pod_controller.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/S, approved

#398 use staging images instead of gcr
  .github/ISSUE_TEMPLATE/new-release.md
  Makefile
  charts/lws/README.md
  charts/lws/values.yaml
  cloudbuild.yaml
  config/manager/kustomization.yaml
  hack/e2e-test.sh
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved
