Repository kubernetes-sigs/lws, pull requests merged in 2025-03, with the labels that each got.

#406 Emphasize the version requirement
  docs/setup/install.md
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#411 Add files to publish helm chart
  Makefile
  charts/lws/values.yaml
  cloudbuild.yaml
  hack/push-chart.sh
Labels: kind/feature, cncf-cla: yes, size/L, lgtm, approved

#421 Changed push-chart.sh to be executable
  hack/push-chart.sh
Labels: kind/bug, size/XS, cncf-cla: yes, lgtm, approved

#422 Adding dependencies for push-chart.sh to Makefile
  Makefile
Labels: kind/bug, size/XS, cncf-cla: yes, lgtm, approved

#424 fix image build toolchain errors
  cloudbuild.yaml
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#417 Run controller-gen only for api and pkg directories
  Makefile
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#416 Inject environment variable LWS_WORKER_INDEX
  api/leaderworkerset/v1/leaderworkerset_types.go
  pkg/utils/pod/pod_utils.go
  pkg/utils/pod/pod_utils_test.go
  test/testutils/util.go
  test/wrappers/wrappers.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#402 Add KEP #257: Leader Only SubGroup
  keps/257-Subgroup-leader-only/README.md
  keps/257-Subgroup-leader-only/kep.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash, kind/documentation

#433 Add Label `leaderworkerset.sigs.k8s.io/name` to the headlessService
  pkg/utils/controller/controller_utils.go
Labels: kind/feature, size/XS, cncf-cla: yes, lgtm, approved

#426 Creating LWS site
  netlify.toml
  site/.gitignore
  site/OWNERS
  site/archetypes/default.md
  site/assets/icons/logo.svg
  site/assets/scss/_styles_project.scss
  site/assets/scss/_variables_project.scss
  site/config.toml
  site/content/en/_index.html
  site/content/en/docs/_index.md
  site/content/en/docs/adoption/_index.md
  site/content/en/docs/concepts/_index.md
  site/content/en/docs/concepts/rollout-strategy/_index.md
  site/content/en/docs/contribution guidelines/_index.md
  site/content/en/docs/installation/_index.md
  site/content/en/docs/search.md
  site/content/en/search.md
  site/layouts/404.html
  site/layouts/partials/feedback.html
  site/layouts/partials/footer.html
  site/layouts/partials/head.html
  site/layouts/partials/navbar-version-selector.html
  site/layouts/partials/navbar.html
  site/layouts/partials/seo_schema.html
  site/layouts/shortcodes/blocks/content-item.html
  site/layouts/shortcodes/blocks/content-section.html
  site/layouts/shortcodes/blocks/link-down.html
  site/layouts/shortcodes/blocks/sample-section.html
  site/layouts/shortcodes/blocks/tab.html
  site/layouts/shortcodes/blocks/tabs.html
  site/layouts/shortcodes/include.html
  site/layouts/shortcodes/needs-update.html
  site/layouts/shortcodes/params.html
  site/layouts/sitemap.xml
  site/package-lock.json
  site/package.json
  site/static/favicons/android-chrome-192x192.png
  site/static/favicons/android-chrome-512x512.png
  site/static/favicons/apple-touch-icon.png
  site/static/favicons/favicon-16x16.png
  site/static/favicons/favicon-32x32.png
  site/static/favicons/favicon.ico
  site/static/favicons/site.webmanifest
  site/static/images/logo.svg
Labels: cncf-cla: yes, lgtm, size/XXL, approved, kind/documentation

#434 Change annotation `leaderworkerset.gke.io/subgroup-size` to `leaderworkerset.sigs.k8s.io/subgroup-size`
  api/leaderworkerset/v1/leaderworkerset_types.go
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#440 updating diagrams to include new logo
  README.md
  site/content/en/docs/concepts/_index.md
Labels: size/XS, cncf-cla: yes, lgtm, approved, kind/documentation

#446 Update README.md to include the logo and website
  README.md
  site/content/en/_index.html
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved

#428 Implementation KEP 257: LeaderExcluded SubGroup
  api/config/v1alpha1/zz_generated.deepcopy.go
  api/config/v1alpha1/zz_generated.defaults.go
  api/leaderworkerset/v1/leaderworkerset_types.go
  api/leaderworkerset/v1/zz_generated.deepcopy.go
  client-go/applyconfiguration/leaderworkerset/v1/subgrouppolicy.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  pkg/controllers/leaderworkerset_controller.go
  pkg/controllers/leaderworkerset_controller_test.go
  pkg/utils/accelerators/tpu.go
  pkg/utils/accelerators/tpu_test.go
  pkg/webhooks/leaderworkerset_webhook.go
  pkg/webhooks/pod_webhook.go
  pkg/webhooks/pod_webhook_test.go
  test/integration/webhooks/leaderworkerset_test.go
  test/wrappers/wrappers.go
Labels: kind/feature, cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash

#445 Use create jobs command instead of run pods in e2e testing
  config/samples/leaderworkerset_exclusiveplacement.yaml
  config/samples/leaderworkerset_multi_template.yaml
  config/samples/leaderworkerset_tpu.yaml
  config/samples/leaderworkerset_v1_leaderworkerset.yaml
  docs/examples/sample/lws-exclusive-placement.yaml
  docs/examples/sample/lws-multi-template.yaml
  docs/examples/sample/lws-restart-policy.yaml
  docs/examples/sample/lws-rollout-strategy.yaml
  docs/examples/sample/lws.yaml
  pkg/controllers/leaderworkerset_controller_test.go
  pkg/controllers/pod_controller_test.go
  site/content/en/docs/concepts/_index.md
  test/e2e/e2e_test.go
  test/integration/controllers/leaderworkerset_test.go
  test/wrappers/wrappers.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/M, approved

#451 Export kind and cluster related logs under artifacts directory for e2e
  hack/e2e-test.sh
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved

#452 update to golang 1.24
  Dockerfile
  docs/examples/llamacpp/tools/blobserver/go.mod
  docs/examples/llamacpp/tools/clichat/go.mod
  docs/examples/llamacpp/tools/llamacpp-leader/go.mod
  go.mod
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved

#457 Set readOnlyRootFilesystem explicitly to true
  charts/lws/values.yaml
  config/manager/manager.yaml
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#450 Fix website layout
  site/content/en/_index.html
Labels: kind/bug, cncf-cla: yes, lgtm, size/M, approved

#453 [Docs] Use the vllm image instead of building by the user self in the sample
  docs/examples/vllm/GPU/lws.yaml
  docs/examples/vllm/TPU/lws.yaml
  docs/examples/vllm/build/Dockerfile.GPU
  docs/examples/vllm/build/Dockerfile.TPU
  docs/examples/vllm/build/ray_init.sh
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved

#455 Cherrypick 319 to release-0.5
  charts/lws/templates/rbac/clusterrole.yaml
Labels: size/XS, cncf-cla: yes, lgtm, approved, ok-to-test

#458 Explicitly bind metrics 8443 as containerPort in kustomize and helm
  charts/lws/templates/manager/deployment.yaml
  charts/lws/templates/manager/service.yaml
  config/default/kustomization.yaml
  config/default/manager_metrics_patch.yaml
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved

#459 Update envtest to use latest
  Makefile
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#460 Add Yankay(myself) as reviewer
  OWNERS
Labels: size/XS, cncf-cla: yes, kind/flake, lgtm, approved

#464 Adding dependabot for npm packages
  .github/dependabot.yml
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved

#468 [Doc] Add troubleshooting page in site
  site/content/en/docs/troubleshooting/_index.md
Labels: cncf-cla: yes, lgtm, size/M, approved, kind/documentation

#439 ignore 0 replica check
  pkg/webhooks/leaderworkerset_webhook.go
  test/integration/webhooks/leaderworkerset_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#469 Remove node.js version in `netlify.toml` for site
  netlify.toml
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#471 Add ardaguclu in reviewers
  OWNERS
Labels: size/XS, cncf-cla: yes, lgtm, approved, kind/documentation

#479 docs: fix image url typo in README.md
  README.md
  site/content/en/docs/overview/_index.md
Labels: size/XS, cncf-cla: yes, lgtm, approved, kind/documentation

#480 Release v0.6.0
  charts/lws/Chart.yaml
  site/config.toml
  site/content/en/docs/installation/_index.md
Labels: size/XS, cncf-cla: yes, lgtm, approved

#481 Fix helm update
  Makefile
  charts/lws/values.yaml
  hack/push-chart.sh
Labels: kind/bug, cncf-cla: yes, lgtm, size/S, approved

#482 Put helm chart under `lws/charts/`
  Makefile
  charts/lws/values.yaml
  config/manager/kustomization.yaml
  hack/push-chart.sh
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved
