Repository kubernetes-sigs/lws, pull requests merged in 2025-09, with the labels that each got.

#647 Update k8s dependencies to 1.34.0
  Makefile
  charts/lws/templates/crds/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  client-go/applyconfiguration/internal/internal.go
  client-go/applyconfiguration/leaderworkerset/v1/leaderworkerset.go
  client-go/applyconfiguration/utils.go
  client-go/clientset/versioned/fake/clientset_generated.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  go.mod
  go.sum
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XXL, approved

#642 chore: add buildDate in driver init logs
  Makefile
  cmd/main.go
  pkg/version/version.go
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#650 chore: add version parameter
  cmd/main.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved

#656 Add Red Hat in adopters
  site/content/en/docs/adoption/_index.md
Labels: size/XS, cncf-cla: yes, lgtm, approved, kind/documentation

#660 test: add codespell github action
  .github/workflows/codespell.yaml
  api/leaderworkerset/scheme/scheme.go
  docs/examples/llamacpp/tools/clichat/cmd/clichat/main.go
  keps/173-headless-service-per-replica/README.md
  keps/238-controller-revision/README.md
  keps/257-Subgroup-leader-only/README.md
  keps/511-partition-update/README.md
  keps/552-worker-resizing/README.md
  keps/622-volume-claim-templates/README.md
  pkg/controllers/leaderworkerset_controller.go
  pkg/controllers/pod_controller.go
  pkg/utils/pod/pod_utils_test.go
  site/content/en/docs/concepts/_index.md
  site/content/en/docs/examples/llamacpp.md
  site/layouts/shortcodes/include.html
  test/e2e/e2e_test.go
  test/integration/controllers/leaderworkerset_test.go
  test/integration/webhooks/pod_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#662 docs: expand SubGroup section with size and LeaderOnly type
  site/content/en/docs/concepts/_index.md
Labels: cncf-cla: yes, lgtm, size/S, approved, kind/documentation, ok-to-test
