Repository kubernetes-sigs/lws, pull requests merged in 2025-05, with the labels that each got.

#520 Fix helm install panic by invalid values `.Values.certManager.enable`
  charts/lws/templates/manager/configmap.yaml
Labels: kind/bug, size/XS, cncf-cla: yes, lgtm, approved, ok-to-test

#525 [doc] fix typo
  site/content/en/docs/manage/cert_manager.md
Labels: size/XS, cncf-cla: yes, lgtm, approved, ok-to-test

#527 Use correct lws apigroup name
  charts/lws/templates/manager/configmap.yaml
Labels: kind/bug, size/XS, cncf-cla: yes, lgtm, approved

#488 Fix issue with rolling update when some existing replicas are unhealthy
  pkg/controllers/leaderworkerset_controller.go
  test/integration/controllers/leaderworkerset_test.go
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash, ok-to-test

#536 Fix lws chart: the webhook service selects unexpected pods when it is introduced as a dependency
  charts/lws/templates/webhook/service.yaml
Labels: kind/bug, size/XS, cncf-cla: yes, lgtm, approved

#530 fix: check optional field not nil before reference
  charts/lws/templates/crds/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  pkg/webhooks/leaderworkerset_webhook.go
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#531 Doc: fix some typo in KEP 115 documents
  keps/115-Subgroup-support/README.md
Labels: size/XS, cncf-cla: yes, lgtm, approved, kind/documentation, ok-to-test

#545 Bump k8s dependencies to 1.33
  Makefile
  charts/lws/templates/crds/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  client-go/clientset/versioned/fake/clientset_generated.go
  client-go/clientset/versioned/typed/leaderworkerset/v1/leaderworkerset_client.go
  client-go/informers/externalversions/leaderworkerset/v1/leaderworkerset.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  go.mod
  go.sum
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XXL, approved, tide/merge-method-squash
