Repository kubernetes-sigs/lws, pull requests merged in 2025-06, with the labels that each got.

#523 fix: support foreground deletion
  pkg/controllers/leaderworkerset_controller.go
  test/e2e/e2e_test.go
  test/testutils/util.go
  test/testutils/validators.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#549 Add dynamo and new presentation
  site/content/en/docs/adoption/_index.md
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#553 Update controller runtime to v0.21.0 and cert-controller to v0.13.
  cmd/main_test.go
  go.mod
  go.sum
  pkg/config/config_test.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved

#555 Automated cherry pick of #536: Fix lws chart: the webhook service selects unexpected pods when it is introduced as a dependency
  charts/lws/templates/webhook/service.yaml
Labels: size/XS, cncf-cla: yes

#561 Automated cherry pick of #482: Put helm chart under `lws/charts/`
  Makefile
  charts/lws/values.yaml
  config/manager/kustomization.yaml
  hack/push-chart.sh
Labels: cncf-cla: yes, lgtm, size/S, approved

#562 Release v0.6.2
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  Makefile
  charts/lws/Chart.yaml
  site/config.toml
  site/content/en/docs/installation/_index.md
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved
