Repository kubernetes-sigs/lws, pull requests merged in 2025-07, with the labels that each got.

#568 fix rolling update stuck that when old pods were not ready
  pkg/controllers/leaderworkerset_controller.go
  test/e2e/e2e_test.go
  test/testutils/util.go
  test/wrappers/wrappers.go
Labels: kind/bug, cncf-cla: yes, kind/regression, lgtm, size/M, approved

#557 KEP #552: allow updates to `spec.leaderWorkerTemplate.size` field
  keps/552-worker-resizing/README.md
  keps/552-worker-resizing/kep.yaml
Labels: kind/feature, cncf-cla: yes, size/L, lgtm, approved, kind/api-change, ok-to-test

#575 Remove workaround for code-generator
  hack/update-codegen.sh
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved

#581 Update vllm.md
  site/content/en/docs/examples/vllm.md
Labels: size/XS, cncf-cla: yes, lgtm, approved, kind/documentation

#582 [talk and slides] adding KubeCon HK and JP 2025 talks for LWS
  site/content/en/docs/adoption/_index.md
Labels: size/XS, cncf-cla: yes, lgtm, approved, ok-to-test

#580 feat: add meaningful printer columns to LeaderWorkerSet CRD
  api/leaderworkerset/v1/leaderworkerset_types.go
  charts/lws/templates/crds/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#496 Add KEP#407: Gang Scheduling
  keps/407-gang-scheduling/README.md
  keps/407-gang-scheduling/gang-scheduling-sequence.png
  keps/407-gang-scheduling/kep.yaml
Labels: cncf-cla: yes, size/XL, lgtm, approved, kind/documentation, ok-to-test

#576 feat: allow updates to spec.leaderWorkerTemplate.size
  Makefile
  api/leaderworkerset/v1/leaderworkerset_types.go
  api/leaderworkerset/v1/zz_generated.deepcopy.go
  charts/lws/templates/crds/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  client-go/applyconfiguration/leaderworkerset/v1/leaderworkertemplate.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  docs/examples/sample/lws.yaml
  keps/552-worker-resizing/README.md
  pkg/webhooks/leaderworkerset_webhook.go
  site/content/en/docs/reference/leaderworkerset.v1.md
  test/e2e/e2e_test.go
  test/integration/controllers/leaderworkerset_test.go
  test/integration/webhooks/leaderworkerset_test.go
  test/testutils/util.go
  test/wrappers/wrappers.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/XXL, approved, kind/api-change, ok-to-test

#594 Default Partition in RollingUpdateConfiguration to 0 to align with spec
  pkg/webhooks/leaderworkerset_webhook.go
Labels: kind/bug, size/XS, cncf-cla: yes, lgtm, approved

#597 Fix: use the main image in helm chart
  Makefile
  charts/lws/values.yaml
  config/manager/kustomization.yaml
Labels: kind/bug, size/XS, cncf-cla: yes, kind/regression, lgtm, approved
