Repository kubernetes-sigs/lws, pull requests merged in 2025-08, with the labels that each got.

#601 fix: don't increase API surface to allow resizing
  api/leaderworkerset/v1/leaderworkerset_types.go
  api/leaderworkerset/v1/zz_generated.deepcopy.go
  charts/lws/templates/crds/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  client-go/applyconfiguration/leaderworkerset/v1/leaderworkertemplate.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  keps/552-worker-resizing/README.md
  pkg/webhooks/leaderworkerset_webhook.go
  site/content/en/docs/reference/leaderworkerset.v1.md
  test/e2e/e2e_gang_scheduling_test.go
  test/e2e/e2e_test.go
  test/integration/controllers/leaderworkerset_test.go
  test/integration/webhooks/leaderworkerset_test.go
  test/wrappers/wrappers.go
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved, ok-to-test

#603 Release 0.7.0
  Makefile
  charts/lws/Chart.yaml
  charts/lws/values.yaml
  site/config.toml
  site/content/en/docs/installation/_index.md
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved

#604 Release 0.7.0
  Makefile
  charts/lws/Chart.yaml
  charts/lws/values.yaml
  site/config.toml
  site/content/en/docs/installation/_index.md
Labels: cncf-cla: yes, lgtm, size/S, approved

#608 Release 0.6.3
  Makefile
  charts/lws/Chart.yaml
  site/config.toml
  site/content/en/docs/installation/_index.md
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved

#612 fix: LLM endpoint port update
  docs/examples/llamacpp/dev/tasks/run-in-kind
Labels: kind/bug, size/XS, cncf-cla: yes, lgtm, approved, ok-to-test

#626 style: 🔨 Maintain a uniform +kubebuilder style in the context.
  pkg/controllers/leaderworkerset_controller.go
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved, ok-to-test

#623 fix: 🐛 Declare the variable CGO_ENABLED in Dockerfile
  Dockerfile
Labels: kind/bug, size/XS, cncf-cla: yes, lgtm, approved, ok-to-test
