Repository kubernetes-sigs/lws, pull requests merged in 2025-01, with the labels that each got.

#297 Tests for Controller Revision
  pkg/controllers/leaderworkerset_controller.go
  pkg/utils/revision/revision_utils.go
  pkg/utils/revision/revision_utils_test.go
  test/integration/controllers/leaderworkerset_test.go
  test/testutils/util.go
  test/testutils/validators.go
Labels: cncf-cla: yes, size/XL, kind/cleanup, lgtm, approved, tide/merge-method-squash

#298 Minimize number of unnecessary logs
  pkg/controllers/leaderworkerset_controller.go
Labels: cncf-cla: yes, lgtm, size/S, approved, tide/merge-method-squash

#300 Update Reference Doc
  docs/reference/leaderworkerset.v1.md
Labels: cncf-cla: yes, lgtm, size/M, approved, kind/documentation

#301 Updating owners
  OWNERS
Labels: size/XS, cncf-cla: yes, lgtm, approved, kind/documentation

#299 Add Events
  api/leaderworkerset/v1/leaderworkerset_types.go
  cmd/main.go
  pkg/controllers/leaderworkerset_controller.go
  pkg/controllers/leaderworkerset_controller_test.go
  pkg/controllers/pod_controller.go
  test/integration/controllers/leaderworkerset_test.go
  test/integration/controllers/suite_test.go
  test/testutils/validators.go
Labels: kind/feature, cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash

#305 Replaced Kueue with LWS on chart/lws ReadMe
  charts/lws/README.md
Labels: size/XS, cncf-cla: yes, lgtm, approved, kind/documentation

#304 Ignore not found error when handling ReacreateGroupOnPodRestart
  pkg/controllers/pod_controller.go
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved, tide/merge-method-squash

#284 Replace kube-rbac-proxy
  cmd/main.go
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_metrics_service.yaml
  config/rbac/auth_proxy_client_binding.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/kustomization.yaml
  go.mod
  go.sum
  test/e2e/e2e_test.go
  test/testutils/util.go
Labels: cncf-cla: yes, size/L, lgtm, kind/deprecation, approved, tide/merge-method-squash, ok-to-test

#306 Fixed flaky ControllerRevision test and add CR events
  pkg/controllers/leaderworkerset_controller.go
  test/integration/controllers/leaderworkerset_test.go
  test/testutils/util.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash

#307 Fixed metrics service port, added log level flag back
  cmd/main.go
  config/default/kustomization.yaml
  config/default/manager_config_patch.yaml
  config/default/manager_metrics_service.yaml
  test/e2e/e2e_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/S, approved, tide/merge-method-squash

#308 Removed kube-rbac-proxy container from helm charts
  charts/lws/templates/manager/deployment.yaml
  charts/lws/templates/manager/service.yaml
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved

#309 Update docs for v0.5.0 release
  charts/lws/Chart.yaml
  docs/setup/install.md
Labels: size/XS, cncf-cla: yes, lgtm, approved

#310 Add public vLLM on TPU image
  docs/examples/vllm/build/Dockerfile.TPU
Labels: size/XS, cncf-cla: yes, lgtm, approved, kind/documentation

#311 Removed dependency to controller-runtime from v1 package
  api/leaderworkerset/scheme/scheme.go
  api/leaderworkerset/v1/groupversion_info.go
Labels: cncf-cla: yes, lgtm, size/M, approved, kind/documentation

#312 Add wg-serving to newsletters in release template
  .github/ISSUE_TEMPLATE/new-release.md
Labels: size/XS, cncf-cla: yes, lgtm, approved, kind/documentation

#313 Refactored wrappers into its own package
  pkg/controllers/leaderworkerset_controller_test.go
  pkg/controllers/pod_controller_test.go
  pkg/utils/accelerators/tpu_test.go
  pkg/utils/pod/pod_utils_test.go
  pkg/utils/revision/revision_utils_test.go
  test/e2e/e2e_test.go
  test/e2e/suite_test.go
  test/integration/controllers/leaderworkerset_test.go
  test/integration/webhooks/leaderworkerset_test.go
  test/integration/webhooks/pod_test.go
  test/wrappers/wrappers.go
Labels: cncf-cla: yes, size/XL, kind/cleanup, lgtm, approved

#314 Update KEP #238 to reflect implementation
  keps/238-controller-revision/README.md
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash, kind/documentation

#319 Add controllerrevisions rbac to helm chart.
  charts/lws/templates/rbac/clusterrole.yaml
Labels: kind/bug, size/XS, cncf-cla: yes, lgtm, approved, ok-to-test

#321 Make lws image multi-platform
  Dockerfile
  Makefile
Labels: kind/feature, cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#326 Removed kube-rbac-proxy from helm charts readme and values.yaml
  charts/lws/README.md
  charts/lws/values.yaml
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved, ok-to-test

#329 Revert "Make lws image multi-platform"
  Dockerfile
  Makefile
Labels: cncf-cla: yes, lgtm, size/S, approved

#330 Revert back #329
  Dockerfile
  Makefile
Labels: kind/bug, cncf-cla: yes, lgtm, size/S, approved

#323 Remove pods create permission
  charts/lws/templates/rbac/clusterrole.yaml
  config/rbac/role.yaml
Labels: kind/feature, cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#335 add junit and artifacts directory for e2e tests so testgrid will disp…
  hack/e2e-test.sh
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#333 update lws to k 1.32
  client-go/applyconfiguration/internal/internal.go
  client-go/applyconfiguration/leaderworkerset/v1/leaderworkerset.go
  client-go/applyconfiguration/leaderworkerset/v1/leaderworkersetstatus.go
  client-go/applyconfiguration/leaderworkerset/v1/leaderworkertemplate.go
  client-go/applyconfiguration/leaderworkerset/v1/networkconfig.go
  client-go/applyconfiguration/leaderworkerset/v1/rolloutstrategy.go
  client-go/clientset/versioned/clientset.go
  client-go/clientset/versioned/typed/leaderworkerset/v1/fake/fake_leaderworkerset.go
  client-go/clientset/versioned/typed/leaderworkerset/v1/fake/fake_leaderworkerset_client.go
  client-go/clientset/versioned/typed/leaderworkerset/v1/leaderworkerset.go
  client-go/clientset/versioned/typed/leaderworkerset/v1/leaderworkerset_client.go
  client-go/informers/externalversions/generic.go
  client-go/informers/externalversions/leaderworkerset/v1/leaderworkerset.go
  client-go/listers/leaderworkerset/v1/leaderworkerset.go
  config/crd/bases/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  go.mod
  go.sum
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XXL, approved

#339 copy the golang code rather than add folders into docker file
  Dockerfile
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, approved

#341 Removed restarting group log in pod controller
  pkg/controllers/pod_controller.go
Labels: size/XS, cncf-cla: yes, kind/cleanup, lgtm, approved

#347 Removed update operation from pod webhook
  charts/lws/templates/webhook/webhook.yaml
  config/webhook/manifests.yaml
  pkg/webhooks/pod_webhook.go
Labels: kind/bug, size/XS, cncf-cla: yes, lgtm, approved

#325 Introduce new component config flag
  PROJECT
  api/config/v1alpha1/configuration_types.go
  api/config/v1alpha1/defaults.go
  api/config/v1alpha1/defaults_test.go
  api/config/v1alpha1/groupversion_info.go
  api/config/v1alpha1/zz_generated.deepcopy.go
  api/config/v1alpha1/zz_generated.defaults.go
  cmd/main.go
  cmd/main_test.go
  config/default/manager_config_patch.yaml
  config/manager/controller_manager_config.yaml
  config/manager/kustomization.yaml
  config/rbac/configuration_editor_role.yaml
  config/rbac/configuration_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/lws_v1alpha1_configuration.yaml
  pkg/cert/cert.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/validation.go
  pkg/config/validation_test.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/XXL, approved, tide/merge-method-squash, ok-to-test

#349 Automated cherry pick of #342: Added handling of nil revision in pod controller
  pkg/controllers/pod_controller.go
Labels: size/XS, cncf-cla: yes, lgtm, approved

#348 Automated cherry pick of #347: Removed update operation from pod webhook
  charts/lws/templates/webhook/webhook.yaml
  config/webhook/manifests.yaml
  pkg/webhooks/pod_webhook.go
Labels: size/XS, cncf-cla: yes, lgtm, approved

#350 Automated cherry pick of #341: Removed restarting group log in pod controller
  pkg/controllers/pod_controller.go
Labels: size/XS, cncf-cla: yes, lgtm, approved

#352 Patches for 0.5.1 release
  charts/lws/templates/webhook/webhook.yaml
  config/webhook/manifests.yaml
  pkg/controllers/pod_controller.go
  pkg/webhooks/pod_webhook.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#354 Remove duplicated label in helm chart: app.kubernetes.io/instance
  charts/lws/templates/_helpers.tpl
  charts/lws/templates/certmanager/certificate.yaml
  charts/lws/templates/manager/deployment.yaml
Labels: kind/bug, cncf-cla: yes, lgtm, size/S, approved, ok-to-test
